platformRepository: https://github.com/syuhei0519/platform-gitops.git
applicationRepository: https://github.com/syuhei0519/application-manifest.git
targetRevision: main
workloadsEnabled: false
observabilityEnabled: false
