platformRepository: https://github.com/syuhei0519/platform-gitops.git
targetRevision: main
runnerChartRepository: https://charts.gitlab.io
runnerChartVersion: 0.92.1
observabilityEnabled: false
prometheusEnabled: false
prometheusChartVersion: 29.35.0
collectorEnabled: false
grafanaEnabled: false
